# Generated by Django 5.0.3 on 2025-01-01 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_app', '0001_initial'),
        ('common', '0001_initial'),
        ('educational_organizations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='educational_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edu_org_of_campus', to='educational_organizations_app.educationalorganizations'),
        ),
        migrations.AddField(
            model_name='campus',
            name='state_province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_of_campus', to='common.state'),
        ),
        migrations.AddField(
            model_name='historicalcampus',
            name='educational_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='educational_organizations_app.educationalorganizations'),
        ),
        migrations.AddField(
            model_name='historicalcampus',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcampus',
            name='state_province',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.state'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('campus_name', 'educational_organization', 'country_code', 'city', 'state_province'), name='unique_campus_details'),
        ),
    ]
