# Generated by Django 5.0.3 on 2025-01-01 09:35

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college_app', '0001_initial'),
        ('common', '0001_initial'),
        ('department_app', '0001_initial'),
        ('educational_organizations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_of_funding', models.CharField(max_length=255)),
                ('number_of_positions_opening', models.IntegerField()),
                ('funding_for', models.CharField(choices=[('EDU_ORG', 'Educational Organization'), ('College', 'College'), ('Department', 'Department'), ('Faculty', 'Faculty'), ('Other', 'Other')], max_length=10)),
                ('funding_for_other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_opportunity_for', models.CharField(choices=[('International', 'International'), ('National', 'National')], max_length=13)),
                ('funding_type', models.CharField(choices=[('TA', 'Teaching Assistantship'), ('RA', 'Research Assistantship'), ('Fellowship', 'Fellowship'), ('Scholarship', 'Scholarship'), ('Other', 'Other')], max_length=12)),
                ('funding_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Other', 'Other')], max_length=7)),
                ('amount_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('web_address', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('funding_open_date', models.DateField()),
                ('funding_end_date', models.DateField()),
                ('benefits', models.ManyToManyField(blank=True, to='funding_app.benefit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_created_by', to=settings.AUTH_USER_MODEL)),
                ('funding_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.document')),
                ('funding_for_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_for_college', to='college_app.college')),
                ('funding_for_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_for_dept', to='department_app.department')),
                ('funding_for_edu_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_for_edu_org', to='educational_organizations_app.educationalorganizations')),
                ('funding_for_faculty_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_for_faculty_member', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('add_department_funding', 'Can add department funding'), ('add_college_funding', 'Can add college funding'), ('add_edu_org_funding', 'Can add educational organization funding'), ('add_faculty_funding', 'Can add faculty funding'), ('add_others_funding', 'Can Add others Funding')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBenefit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical benefit',
                'verbose_name_plural': 'historical benefits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFunding',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('title_of_funding', models.CharField(max_length=255)),
                ('number_of_positions_opening', models.IntegerField()),
                ('funding_for', models.CharField(choices=[('EDU_ORG', 'Educational Organization'), ('College', 'College'), ('Department', 'Department'), ('Faculty', 'Faculty'), ('Other', 'Other')], max_length=10)),
                ('funding_for_other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_opportunity_for', models.CharField(choices=[('International', 'International'), ('National', 'National')], max_length=13)),
                ('funding_type', models.CharField(choices=[('TA', 'Teaching Assistantship'), ('RA', 'Research Assistantship'), ('Fellowship', 'Fellowship'), ('Scholarship', 'Scholarship'), ('Other', 'Other')], max_length=12)),
                ('funding_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Other', 'Other')], max_length=7)),
                ('amount_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('web_address', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('funding_open_date', models.DateField()),
                ('funding_end_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('funding_doc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.document')),
                ('funding_for_college', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='college_app.college')),
                ('funding_for_dept', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department_app.department')),
                ('funding_for_edu_org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='educational_organizations_app.educationalorganizations')),
                ('funding_for_faculty_member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical funding',
                'verbose_name_plural': 'historical fundings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
